### ISSUE TITLE
Blank Images (Cron Invoices) vs OK (Manual Invoices)

### ISSUE THREAD

**Issue by digitalhybrid** [The-Network-Crew/BPAY-for-WHMCS#1]
We have glaring bug that remains, which threatens the operational viability of this module if left unfixed.

Images are created successfully if a customer's PDF invoice is manually generated, but if the images creation is left to the WHMCS cron, then all we end up with are blank images containing no Biller ID or CRN.

So, in my opinion, this is what I think needs to happen ...

When the module has its CRN generation process configured for the first time, eg, selecting Westpac, EziDebit, etc, or when changing that method, when the Admin clicks the Save button and confirms the modal warning, the module should immediately and automatically generate all images, each containing the Biller ID and CRN.

The Manually Generate CRNs button should be changed to Manually Regenerate CRNs . When this button is clicked, all existing generated images should first be deleted from the relevant directory, and then all new images should be generated to replace them.

This same process should also automatically take place if or whenever the CRN generation method is changed and Saved.

I say all this because I think we need to minimise how many actions need to be taken manually by an admin, otherwise it may just generate unnecessary support requests for you.

I think it would also be good to have the same CRN Prefix field available in each of the generation method options, ie, from Manual through to Westpac, so that the manual editing of the gateway file will never be necessary. This would allow for an identifier if, like us, a company is running multiple WHMCS installations, but all BPay payments resolve to the same bank account. Having a prefix identifier in place will make payment allocation easy and at-a-glance.

I believe the CRN Prefix field option needs to be active if it's populated and look like this ...

prefix + padded zeroes + chosen variable, ie, invoice or client = 10002349

Otherwise, if it's left blank, the result should look like this ...

padded zeroes + chosen variable, ie, invoice or client = 00002349

Forgive me if that sounds like me telling Grandma how to suck eggs, but I'd rather be detailed than leave you guys guessing what's meant.

**Comment by theozsnowman** [comment]
we have had the same ongoing issue for a long time and Clint tried his best to help us resolve the issue however we are still no closer to a solution so we are going to look at resolving this internally and i will post what we find

**Comment by digitalhybrid** [comment]
While we appreciated his efforts, we simply couldn't wait for Clinton any longer, nor could we live in hope that someone might get around to making a contribution to the code here on GitHub. We needed the module in production, and thankfully, we managed to have it ready for last weekend's launch of our new site and its rebrand.

Thankfully we now have an outstanding developer on tap, so we've managed to fix this issue and a small range of others we found, along with adding some enhancements to the module. It's working very well now, but we're not ready at this time to release the updated code into the wild.

**Comment by beanonymous** [comment]
digitalhybrid, I do understand you have put in your own business time & funds into the outsourcing of a contractor to fix the bug in question but I would appreciate it, if you at least put the bug fix issue raised by your self to this repository. 

Other wise I will not be releasing the iCRN feature I have been working on in the background, as I do not see a reason to spent my valuable time on this project if users are not willing to contribute there results to the rest of the community.

We do not necessarily need your enhancements just he bug fix.

Thanks in advance

**Comment by digitalhybrid** [comment]
I'll look at doing that as soon as I'm convinced the few extra enhancements we're adding won't interfere with the bug fix and everything is working as expected.

**Comment by oempire** [comment]
Hi All how did you ever go with this? was there a fix released?

As a note and in the spirit of open source @digitalhybrid your obligated to share the fix

"Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. "

its disappointing that you have violated this - seeing as you additionally used the core obviously for commercial gain. Its not what open source is about.

**Comment by lsthompson** [comment]
Hi @beanonymous & @digitalhybrid -

Following on from @oempire are either of you any closer to releasing your respective improvements to the module?

It would be great to see it improved and made properly viable, as it's never had those final rough edges ironed out.

Hopefully you find a moment amidst the craziness of 2021.

Thank you.

**Comment by lsthompson** [comment]
Potential to generate CRNs for clients using post-cron hook:

https://developers.whmcs.com/hooks-reference/cron/

**Comment by bakkbone** [comment]
Has anyone had any luck with this? I'm starting to see invoices with blank images on my instance too

**Comment by lsthompson** [comment]
@theozsnowman - did you ever make any strides towards resolving this? Contributions would be appreciated.

@digitalhybrid - you have a ticket from us on 30 May 2022 that remains open and without reply.

This is long-standing & it would be great to keep it collaborative. Thank you.

**Comment by lsthompson** [comment]
There could be a correlation between this & Issue #9 - @digitalhybrid reports it may self-resolve after the 1st send.

**We can sadly confirm that v2.2.0 does not resolve this.** We have changed the hook-point back, raised a ticket with WHMCS, and will continue exploring. There is a lot of discourse online about the cron hook points being unreliable via-cron (only), though overall it seems stable in recent times. Will get feedback before continuing with debugging.

**_ID GENERATION METHOD_**

Our set-up uses CRN via Client ID, so there is no case for the issue being due to poorly-timed image generation, as the image was already generated and stored before the daily cron execution. So most likely it's something hook-related.

**_PDF TPL FILE LOCATIONS_**

In our case, there were invoicepdf.tpl/quotepdf.tpl files present in /templates/ as well as /templates/our_template/ - these were aged but the same as our regular PDF TPL files, except that BPAY Manager had of course not injected them with content. I'm wondering if there's a potential for WHMCS to use files from the /templates/ folder with higher priority than template files within the template folder itself (ie. six), if they exist in the parent folder. Will let crons run and see _(no!)._

This seems plausible given the wording used here: https://docs.whmcs.com/PDF_Invoice_Customisation#Template_Files

**_INVOCATION METHOD (HOOKS)_**

I'm confident this relates to method of invocation. The /includes/hooks/bpay_mgr_inc.php file doesn't use great logic to include & call the hooks, and there are differences both with PHP & WHMCS when system invokes compared to when user invokes. `$_SERVER['DOCUMENT_ROOT']` (and other parts of the superglobal) are not available on system-invoke inside PHP (ie. CLI). With WHMCS, I believe it is executing this from another location (ie. if cron.php is outside/above public_html) which is breaking the if-try logic in the module. We've amended the debug code now as it seemed to be failing as well (hah), and have moved to using `__DIR__` on the first if-try to see what that brings up. It should now debug `getcwd()` which will help compare where it's executing from on the next cron run (from above/outside public_html) against customer-initiated (within public_html).

Ref 1: https://stackoverflow.com/questions/8668776/get-root-directory-path-of-a-php-project
Ref 2: https://stackoverflow.com/questions/34005286/how-to-get-the-whmcs-root-directory
Ref 3: https://gist.github.com/ericrasch/dee85f069b1e7a3c4a90 (how to find reliable path)

**_ROOTDIR RELATIVITY BASED ON INVOCATION_**

Changing to leveraging `__DIR__` seems promising in that it works under all invocation methods, however I believe the same problem that was leading to inconsistent hook firing is prevalent through the code's usage of `ROOTDIR` to include/require critical PHP/JPG files in the code-base. I think this will all need slight refactoring as well.

We will do some testing and look to deploy a new global that provides the proper directory regardless of the method of invocation. As WHMCS recommends you move cron.php above/outside public_html, this alongside the subtle differences in PHP (when using CLI/automation) means it can't pull in the critical files, even though the hook is registered (after we debugged the hook execution part of the problem). WHMCS were very little help, so we will update here as we go.

Note 1: Environment variables are different during cron invocations of PHP.
Note 2: Some may have success if their cron is not secured (ie. remains in public_html).
Note 3: We have resolved the hook calls not firing on-cron (dev-only), just image-in-PDF to go.

**_ABSOLUTE/RELATIVE DIR PATHS/REFERENCES_**

Similar to the environmental differences, there could be a difference in how file/folder paths are being interpreted depending on usage throughout the codebase. This needs more attention and troubleshooting.

**_Q2 2023 WORKINGS_**

Consider using `chdir` to move away from cron dir, into modules/gateway directory.

Consider printing environment variables to assist with debugging across invocation methods:
`file_put_contents('env.log', print_r($_ENV, true));`

Image is present, overlaid text is not. Internally we're now testing v2.2.1 and working to resolve the issue.

[WHMCS Community - Thread about this issue](https://whmcs.community/topic/324225-module-works-ok-if-manually-invoked-not-ok-if-cron-invoked-environment-variables-etc/)

`$_SERVER` superglobal may be different to expected, a la `generateImage` function using this to discern cron-or-user being the main example. Also worth debugging via `invoicepdf.tpl` to see if/where it's able to reach.

It's a shame that some users claim to have fixed the issue and choose to disrespect FOSS. It says a lot about them.

**Comment by lsthompson** [comment]
**_We've released v3 branch now, which radically simplifies BPAY for WHMCS. All new code._**

To begin with, it simply provides a CRN merge field for either generation method.

You can then use the variable in Invoice-related Email Templates.

With time, we'll bring back the images & so on.
